#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "bench/parsers/lexbor/utils/lexbor/html/data/entities.json"
OUT = Path(__file__).with_name("data.zig")
NAMED_OUT = ROOT / "src/html/named_entities.zig"
EMPTY = 0xFFFF


def fnv1a(value: bytes) -> int:
    h = 2166136261
    for byte in value:
        h = ((h ^ byte) * 16777619) & 0xFFFFFFFF
    return h


raw = json.loads(SOURCE.read_text())
items = [(key[1:].encode(), value["characters"].encode()) for key, value in raw.items()]
items.sort(key=lambda item: (len(item[0]), item[0]))

name_blob = bytearray()
value_blob = bytearray()
entries = []
for name, value in items:
    ns = len(name_blob)
    vs = len(value_blob)
    name_blob.extend(name)
    value_blob.extend(value)
    entries.append((ns, len(name), vs, len(value)))

shards = [(0, 0, 0) for _ in range(33)]
slots = []
for length in range(2, 33):
    indexes = [i for i, item in enumerate(items) if len(item[0]) == length]
    if not indexes:
        continue
    cap = 1
    while cap * 7 < len(indexes) * 10:
        cap *= 2
    start = len(slots)
    table = [EMPTY] * cap
    for index in indexes:
        pos = fnv1a(items[index][0]) & (cap - 1)
        while table[pos] != EMPTY:
            pos = (pos + 1) & (cap - 1)
        table[pos] = index
    slots.extend(table)
    shards[length] = (start, cap, cap - 1)


class TNode:
    def __init__(self):
        self.children = {}
        self.value = EMPTY


def make_trie(sharded: bool):
    roots = [TNode() for _ in range(33)] if sharded else [TNode()]
    for index, (name, _) in enumerate(items):
        node = roots[len(name)] if sharded else roots[0]
        for byte in name:
            node = node.children.setdefault(byte, TNode())
        node.value = index

    nodes = []
    edges = []

    def emit(node):
        index = len(nodes)
        nodes.append(None)
        child_indexes = [(byte, emit(child)) for byte, child in sorted(node.children.items())]
        edge_start = len(edges)
        edges.extend(child_indexes)
        nodes[index] = (edge_start, len(child_indexes), node.value)
        return index

    root_indexes = [emit(root) for root in roots]
    return root_indexes, nodes, edges


sharded_roots, sharded_nodes, sharded_edges = make_trie(True)
full_roots, full_nodes, full_edges = make_trie(False)


def ints(values):
    return ",".join(str(value) for value in values)


with OUT.open("w") as out:
    out.write("// Generated by generate.py from the WHATWG entity table.\n")
    out.write("pub const empty: u16 = 0xffff;\n")
    out.write("pub const Entry = struct { name_start: u32, name_len: u8, value_start: u32, value_len: u8 };\n")
    out.write("pub const Shard = struct { start: u16, cap: u16, mask: u16 };\n")
    out.write("pub const Node = struct { edge_start: u16, edge_count: u8, value: u16 };\n")
    out.write("pub const Edge = struct { byte: u8, child: u16 };\n")
    out.write(f"pub const names = [_]u8{{{ints(name_blob)}}};\n")
    out.write(f"pub const values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("pub const entries = [_]Entry{\n")
    for row in entries:
        out.write(f".{{.name_start={row[0]},.name_len={row[1]},.value_start={row[2]},.value_len={row[3]}}},\n")
    out.write("};\n")
    out.write("pub const shards = [_]Shard{\n")
    for row in shards:
        out.write(f".{{.start={row[0]},.cap={row[1]},.mask={row[2]}}},\n")
    out.write("};\n")
    out.write(f"pub const slots = [_]u16{{{ints(slots)}}};\n")
    for prefix, roots, nodes, edges in (
        ("sharded", sharded_roots, sharded_nodes, sharded_edges),
        ("full", full_roots, full_nodes, full_edges),
    ):
        out.write(f"pub const {prefix}_roots = [_]u16{{{ints(roots)}}};\n")
        out.write(f"pub const {prefix}_nodes = [_]Node{{\n")
        for row in nodes:
            out.write(f".{{.edge_start={row[0]},.edge_count={row[1]},.value={row[2]}}},\n")
        out.write("};\n")
        out.write(f"pub const {prefix}_edges = [_]Edge{{\n")
        for row in edges:
            out.write(f".{{.byte={row[0]},.child={row[1]}}},\n")
        out.write("};\n")

print(f"generated {OUT}: {len(items)} entries, {len(slots)} hash slots, "
      f"{len(sharded_nodes)} sharded nodes, {len(full_nodes)} full nodes")

with NAMED_OUT.open("w") as out:
    out.write("// Generated by bench/entity_lookup/generate.py from the WHATWG entity table.\n")
    out.write("const std = @import(\"std\");\n")
    out.write("const Empty: u16 = 0xffff;\n")
    out.write("const Entry = struct { name_start: u32, name_len: u8, value_start: u32, value_len: u8 };\n")
    out.write("const Shard = struct { start: u16, cap: u16, mask: u16 };\n")
    out.write(f"const Names = [_]u8{{{ints(name_blob)}}};\n")
    out.write(f"const Values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("const Entries = [_]Entry{\n")
    for row in entries:
        out.write(f".{{.name_start={row[0]},.name_len={row[1]},.value_start={row[2]},.value_len={row[3]}}},\n")
    out.write("};\nconst Shards = [_]Shard{\n")
    for row in shards:
        out.write(f".{{.start={row[0]},.cap={row[1]},.mask={row[2]}}},\n")
    out.write(f"}};\nconst Slots = [_]u16{{{ints(slots)}}};\n")
    out.write(r'''
fn hash(name: []const u8) u32 {
    var h: u32 = 2166136261;
    for (name) |byte| h = (h ^ byte) *% 16777619;
    return h;
}

pub fn lookup(name: []const u8) ?[]const u8 {
    if (name.len >= Shards.len) return null;
    const shard = Shards[name.len];
    if (shard.cap == 0) return null;
    var pos: u16 = @intCast(hash(name) & shard.mask);
    while (true) : (pos = (pos + 1) & shard.mask) {
        const index = Slots[shard.start + pos];
        if (index == Empty) return null;
        const entry = Entries[index];
        const stored = Names[entry.name_start..][0..entry.name_len];
        if (std.mem.eql(u8, stored, name)) return Values[entry.value_start..][0..entry.value_len];
    }
}

pub fn longestPrefix(rem: []const u8, comptime attribute: bool) ?struct { consumed: u8, value: []const u8 } {
    var len = @min(rem.len, 32);
    while (len >= 2) : (len -= 1) {
        const candidate = rem[0..len];
        const value = lookup(candidate) orelse continue;
        if (comptime attribute) {
            if (candidate[candidate.len - 1] != ';' and len < rem.len and
                (std.ascii.isAlphanumeric(rem[len]) or rem[len] == '=')) continue;
        }
        return .{ .consumed = @intCast(len + 1), .value = value };
    }
    return null;
}

test "generated named entity lookup" {
    try std.testing.expectEqualStrings("\xc2\xa0", lookup("nbsp;").?);
    try std.testing.expectEqualStrings("\xe2\xaa\xa2\xcc\xb8", lookup("NotNestedGreaterGreater;").?);
}
''')

print(f"generated {NAMED_OUT}")
