#!/usr/bin/env python3
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "bench/parsers/lexbor/utils/lexbor/html/data/entities.json"
OUT = Path(__file__).with_name("data.zig")
NAMED_OUT = ROOT / "src/html/named_entities.zig"
EMPTY = 0xFFFF


raw = json.loads(SOURCE.read_text())
items = [(key[1:].encode(), value["characters"].encode()) for key, value in raw.items()]
items.sort(key=lambda item: (len(item[0]), item[0]))

name_blob = bytearray()
value_blob = bytearray()
entries = []
for name, value in items:
    ns = len(name_blob)
    vs = len(value_blob)
    name_blob.extend(name)
    value_blob.extend(value)
    entries.append((ns, len(name), vs, len(value)))

def ints(values):
    return ",".join(str(value) for value in values)


with OUT.open("w") as out:
    out.write("// Generated by generate.py from the WHATWG entity table.\n")
    out.write("pub const empty: u16 = 0xffff;\n")
    out.write("pub const Entry = struct { name_start: u32, name_len: u8, value_start: u32, value_len: u8 };\n")
    out.write(f"pub const names = [_]u8{{{ints(name_blob)}}};\n")
    out.write(f"pub const values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("pub const entries = [_]Entry{\n")
    for row in entries:
        out.write(f".{{.name_start={row[0]},.name_len={row[1]},.value_start={row[2]},.value_len={row[3]}}},\n")
    out.write("};\n")
hash_run = subprocess.run(
    ["rtk", "proxy", "zig", "run", str(Path(__file__).with_name("std_hashes.zig")), "-O", "ReleaseFast"],
    cwd=ROOT,
    text=True,
    capture_output=True,
    check=True,
)
std_hashes = [int(line) for line in hash_run.stderr.splitlines() if line.isdigit()]
if len(std_hashes) != len(items):
    raise RuntimeError(f"expected {len(items)} std hashes, got {len(std_hashes)}")

shards = [(0, 0, 0) for _ in range(33)]
slots = []
for length in range(2, 33):
    indexes = [i for i, item in enumerate(items) if len(item[0]) == length]
    if not indexes:
        continue
    cap = 1
    while cap * 7 < len(indexes) * 10:
        cap *= 2
    start = len(slots)
    table = [EMPTY] * cap
    for index in indexes:
        pos = std_hashes[index] & (cap - 1)
        while table[pos] != EMPTY:
            pos = (pos + 1) & (cap - 1)
        table[pos] = index
    slots.extend(table)
    shards[length] = (start, cap, cap - 1)

full_cap = 1
while full_cap * 7 < len(items) * 10:
    full_cap *= 2
full_slots = [EMPTY] * full_cap
for index, value_hash in enumerate(std_hashes):
    pos = value_hash & (full_cap - 1)
    while full_slots[pos] != EMPTY:
        pos = (pos + 1) & (full_cap - 1)
    full_slots[pos] = index

std_cap = 1
while std_cap * 80 // 100 < len(items):
    std_cap *= 2
std_slots = [EMPTY] * std_cap
std_meta = [0] * std_cap
for index, value_hash in enumerate(std_hashes):
    fingerprint = (value_hash >> 56) or 1
    pos = value_hash & (std_cap - 1)
    while std_meta[pos] != 0:
        pos = (pos + 1) & (std_cap - 1)
    std_slots[pos] = index
    std_meta[pos] = fingerprint

with OUT.open("a") as out:
    out.write("pub const Shard = struct { start: u16, cap: u16, mask: u16 };\n")
    out.write("pub const shards = [_]Shard{\n")
    for row in shards:
        out.write(f".{{.start={row[0]},.cap={row[1]},.mask={row[2]}}},\n")
    out.write("};\n")
    out.write(f"pub const slots = [_]u16{{{ints(slots)}}};\n")
    out.write(f"pub const full_hash_mask: u16 = {full_cap - 1};\n")
    out.write(f"pub const full_hash_slots = [_]u16{{{ints(full_slots)}}};\n")
    out.write(f"pub const std_hash_mask: u16 = {std_cap - 1};\n")
    out.write(f"pub const std_slots = [_]u16{{{ints(std_slots)}}};\n")
    out.write(f"pub const std_meta = [_]u8{{{ints(std_meta)}}};\n")
print(f"generated {OUT}: {len(items)} entries, {len(slots)} sharded Wyhash slots")

with NAMED_OUT.open("w") as out:
    out.write("// Generated by bench/entity_lookup/generate.py from the WHATWG entity table.\n")
    out.write("const std = @import(\"std\");\n")
    out.write("const Entry = struct { name_start: u32, name_len: u8, value_start: u32, value_len: u8 };\n")
    out.write(f"const Names = [_]u8{{{ints(name_blob)}}};\n")
    out.write(f"const Values = [_]u8{{{ints(value_blob)}}};\n")
    out.write("const Entries = [_]Entry{\n")
    for row in entries:
        out.write(f".{{.name_start={row[0]},.name_len={row[1]},.value_start={row[2]},.value_len={row[3]}}},\n")
    out.write(f"}};\nconst Slots = [_]u16{{{ints(std_slots)}}};\n")
    out.write(f"const Meta = [_]u8{{{ints(std_meta)}}};\n")
    out.write(f"const Mask: u16 = {std_cap - 1};\n")
    out.write(r'''
pub fn lookup(name: []const u8) ?[]const u8 {
    const value_hash = std.hash.Wyhash.hash(0, name);
    const raw_fingerprint: u8 = @intCast(value_hash >> 56);
    const fingerprint = if (raw_fingerprint == 0) 1 else raw_fingerprint;
    var pos: u16 = @intCast(value_hash & Mask);
    while (Meta[pos] != 0) : (pos = (pos + 1) & Mask) {
        if (Meta[pos] != fingerprint) continue;
        const index = Slots[pos];
        const entry = Entries[index];
        const stored = Names[entry.name_start..][0..entry.name_len];
        if (std.mem.eql(u8, stored, name)) return Values[entry.value_start..][0..entry.value_len];
    }
    return null;
}

pub fn longestPrefix(rem: []const u8, comptime attribute: bool) ?struct { consumed: u8, value: []const u8 } {
    var len = @min(rem.len, 32);
    while (len >= 2) : (len -= 1) {
        const candidate = rem[0..len];
        const value = lookup(candidate) orelse continue;
        if (comptime attribute) {
            if (candidate[candidate.len - 1] != ';' and len < rem.len and
                (std.ascii.isAlphanumeric(rem[len]) or rem[len] == '=')) continue;
        }
        return .{ .consumed = @intCast(len + 1), .value = value };
    }
    return null;
}

test "generated named entity lookup" {
    try std.testing.expectEqualStrings("\xc2\xa0", lookup("nbsp;").?);
    try std.testing.expectEqualStrings("\xe2\xaa\xa2\xcc\xb8", lookup("NotNestedGreaterGreater;").?);
}
''')

print(f"generated {NAMED_OUT}")
